# Skeleton joints indices
# As if we are behind the person
# (their left is our left)
#          3-1   2-4
#             \ /
#              0
#              |
#       5-------------6
#       |    |   |    |
#	    |    |   |    |
#       7    |   |    8
#       |    |   |    |
#       |    |   |    |
#       9   11   12   10
#            |   |
#            |   |
#            |   |
#           13   14
#            |   |
#            |   |
#            |   |
#           15   16
zed_yolo_ros/Keypoint3D[17] keypoints
